version: "2"

services:

    {{ application.name }}:
        container_name: {{ application.name }}
        build: ./
        ports:
            - {{ container.port }}:80
        volumes:
            - ..:/var/www/{{ application.name }}
            - ./conf/{{ server.type }}:/etc/{{ server.type }}
            - ./conf/php7:/etc/php7
            - ./extra/php7:/usr/lib/php7
