version: "2"

services:

    nginx:
        container_name: nginx
        image: nginx:alpine
        working_dir: /var/www/nginx
        restart: always
        environment:
            APPLICATION_NAME: nginx
            SERVER_NAME: dev.toto.io
            DOCUMENT_ROOT: .
            DIRECTORY_INDEX: index.php
            PHP_CONTAINER_NAME: php
        volumes:
            - ..:/var/www/nginx
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./conf/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:80
        links:
          - php

    php:
        container_name: php
        image: php:fpm-alpine
        working_dir: /var/www/nginx
        restart: always
        volumes:
            - ..:/var/www/nginx
        ports:
            - 9000:9000

