version: "2"

services:

    {{ application.name }}:
        container_name: {{ application.name }}
        image: nginx:{{ image.version }}
        working_dir: /var/www/{{ application.name }}
        restart: always
        volumes:
            - ..:/var/www/{{ application.name }}
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - ./conf/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - {{ port }}:80
        links:
          - {{ php.container.name }}

    {{ php.container.name }}:
        container_name: {{ php.container.name }}
        image: php:{{ php.image.version }}
        working_dir: /var/www/{{ application.name }}
        restart: always
        volumes:
            - ..:/var/www/{{ application.name }}
        ports:
            - {{ php.port }}:9000
