    {{ container.name }}:
        container_name: {{ container.name }}
        image: adminer:{{ image.version }}
        restart: always
        environment:
            ADMINER_PLUGINS={{ plugins }}
            ADMINER_DESIGN={{ design }}
        ports:
            - {{ port }}:8080

