    {{ container.name }}:
        container_name: {{ container.name }}
        image: alpine:{{ image.version }}
        working_dir: /var/www/{{ container.name }}
        restart: always
        volumes:
            - {{ application.dir }}:/var/www/{{ container.name }}
        # Comment this line if you don't want to keep container running
        command: "tail -f /dev/null"
