    {{ container.name }}:
        container_name: {{ container.name }}
        image: composer
        restart: always
        volumes:
            - ..:/app
        # Uncomment the line below if you want to run the 'composer update' command when the container starts.
        #command: ["composer", "update"]
        # Comment this line if you don't want to keep container running
        command: "tail -f /dev/null"
