{{ CONTAINER_NAME }}:
    container_name: {{ CONTAINER_NAME }}
    image: mariadb:10.3
    restart: always
    volumes:
        - {{ STORAGE }}:/var/lib/mysql
        - ./conf/mariadb:/etc/mysql
    environment:
        MYSQL_DATABASE: {{ DATABASE_NAME }}
        MYSQL_USER: {{ USER }}
        MYSQL_PASSWORD: {{ PASSWORD }}
        MYSQL_ROOT_PASSWORD: {{ ROOT_PASSWORD }}