    {{ container.name }}:
        container_name: {{ container.name }}
        image: mariadb:10.3
        restart: always
        volumes:
            - {{ storage }}:/var/lib/mysql
            - ./conf/mariadb:/etc/mysql
        environment:
            MYSQL_DATABASE: {{ database.name }}
            MYSQL_USER: {{ user }}
            MYSQL_PASSWORD: {{ password }}
            MYSQL_ROOT_PASSWORD: {{ root.password }}
