    {{ container.name }}:
        container_name: {{ container.name }}
        build: ./conf/node-slim
        working_dir: /var/www/{{ container.name }}
        restart: always
        volumes:
            - {{ application.dir }}:/var/www/{{ container.name }}
        command: "tail -f /dev/null"
