    {{ container.name }}:
        container_name: {{ container.name }}
        image: node:alpine
        user: {{ user }}
        working_dir: /home/{{ user }}/app
        restart: always
        volumes:
            - {{ APPLICATION_DIR }}:/home/{{ user }}/app
        environment:
            NODE_ENV: {{ env }}
        expose:
            - {{ port }}
        command: 'npm start'
