    {{ container.name }}:
        container_name: {{ container.name }}
        image: node:{{ image.version }}-alpine
        user: "node"
        working_dir: /home/node/app
        restart: always
        volumes:
            - {{ application.dir }}:/home/node/app
        environment:
            NODE_ENV: {{ env }}
        expose:
            - {{ port }}
        # Uncomment the line below if you want to run the 'npm start' command when the container starts.
        #command: "npm start"
        # Uncomment this line if you don't want to keep container running
        command: "tail -f /dev/null"
