    {{ container.name }}:
        container_name: {{ container.name }}
        image: php:{{ image.version }}
        working_dir: /var/www/app
        restart: always
        volumes:
            - {{ application.dir }}:/var/www/app
        ports:
            {{ port }}:9000
