    {{ container.name }}:
        container_name: {{ container.name }}
        image: php:{{ version }}-fpm-alpine
        working_dir: /var/www/app
        restart: always
        volumes:
            - ..:/var/www/app
            - ./conf/php:/etc/php{{ version }}
            - ./extra/php:/usr/lib/php{{ version }}
        ports:
            {{ port }}:9000
