    {{ container.name }}:
        container_name: {{ container.name }}
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
          - PMA_USER={{ user }}
          - PMA_PASSWORD={{ password }}
        ports:
            - {{ port }}:80
        links:
            -{{ database.container.name }}:db
