    {{ container.name }}:
        container_name: {{ container.name }}
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: {{ user }}
            POSTGRES_PASSWORD: {{ password }}
            POSTGRES_DB: {{ database.name }}
            PGDATA: {{ database.storage.location }}
        ports:
            - {{ port }}:5432
