    {{ container.name }}:
        container_name: {{ container.name }}
        image: redis:{{ image.version }}
        restart: always
        volumes:
            - {{ database.storage.location }}:/data
        ports:
            - {{ port }}:6379
