    {{ container.name }}:
        container_name: {{ container.name }}
        image: ubuntu:{{ image.version }}
        working_dir: {{ application.dir }}
        restart: always
        # Comment this line if you don't want to keep container running
        command: "tail -f /dev/null"
