version: "2"

services:

    {{ application.name }}:
        container_name: {{ application.name }}
        build: ./
        ports:
            - {{ port }}:80
        volumes:
            - ..:/var/www/{{ application.name }}
            - ./conf/{{ server.type }}:/etc/{{ server.type }}
            - ./conf/php{{ php.version }}:/etc/php{{ php.version }}
            - ./extra/php{{ php.version }}:/usr/lib/php{{ php.version }}
