version: "2"

services:

    {{ application.name }}:
        container_name: {{ application.name }}
        build: ./
        ports:
            - {{ port }}:80
        volumes:
            - ..:/var/www/{{ application.name }}
            - ./conf/{{ server.type }}:/etc/{{ server.type }}
#            - ./conf/php:/etc/php{{ php.version }}:ro
            - ./conf/php/php.ini:/etc/php{{ php.version }}/php.ini:ro
            - ./extra/php{{ php.version }}:/usr/lib/php{{ php.version }}
